spring:
  datasource:
    url: ${POSTGRES_CONNECTION_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  kafka:
    consumer-default-topic: ${DEFAULT_CONSUMER_TOPIC_NAME:handler_analyzer_processed-data-event}
    producer-default-topic: ${DEFAULT_PRODUCER_TOPIC_NAME:analyzed-messages}
    consumer:
      group-id: ${MESSAGE_CONSUMER_GROUP:app.2}
      bootstrap-servers: ${BOOTSTRAP_HOST:localhost:29092}
server:
  port: 8085
